### ISSUE TITLE
Add GitHub Action to update example page

### ISSUE THREAD

**Issue by christian-bromann** [saucelabs/network-viewer#52]
Currently it doesn't seem that the [example page](https://opensource.saucelabs.com/network-viewer/) is updated automatically for every release. With GitHub Actions this can be achieved easily. Please have a look at this example:

```
name: Publish Example Site

on:
  push:
    tags:
      - v*

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ...
          publish_branch: ...
          user_name: 'OSS Sauce Bot'
          user_email: 'oss-sauce-bot@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
```
